export const metadata = {
  title: "Login - Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="relative h-screen">
      <main className="mx-auto max-w-4xl px-8 py-24">{children}</main>
    </div>
  );
}
