import { Header } from "@/components/Header";
import "./globals.css";
import { Poppins } from "next/font/google";
const poppins = Poppins({ weight: ["100", "400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br" className={poppins.className}>
      <body className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="relative h-screen">
          <Header />
          <main className="py-24 max-w-4xl px-8 mx-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
